# Generated by Django 4.2 on 2024-07-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='city',
            new_name='city_flight',
        ),
    ]
