# Generated by Django 4.2 on 2024-07-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_cit1_ticket_city_arrived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeroport',
            name='aeroport',
            field=models.CharField(max_length=30),
        ),
    ]
