# Generated by Django 4.2 on 2024-07-17 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_buy_ticket_ticket_remove_ticket_aeroport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy_ticket',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='aeroport',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='bag',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='city_arrived',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='city_flight',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='plane',
        ),
        migrations.AddField(
            model_name='buy_ticket',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='aeroport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.aeroport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='bag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.bag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='city_arrived',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.cit1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='city_flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='plane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.plane'),
            preserve_default=False,
        ),
    ]
