# Generated by Django 4.2 on 2024-07-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_buy_ticket_ticket_remove_ticket_aeroport_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buy_ticket',
            new_name='Passenger',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='city_arrived',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrived_sity', to='tickets.city'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='city_flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departiva_city', to='tickets.city'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.DeleteModel(
            name='Cit1',
        ),
    ]
