# Generated by Django 4.2 on 2024-07-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_rename_buy_ticket_passenger_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='flight_date',
            new_name='departure_date',
        ),
    ]
