# Generated by Django 4.2 on 2024-07-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_rename_flight_date_ticket_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bag',
            field=models.CharField(choices=[('on', 'ON'), ('off', 'OFF')], default='off', max_length=3),
        ),
        migrations.DeleteModel(
            name='Bag',
        ),
    ]
